name: weather_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  lottie: ^2.6.0
  supabase_flutter: ^1.10.14
  animations: ^2.0.8
  shimmer: ^3.0.0
  flutter_bloc: ^8.1.3
  flutter_staggered_animations: ^1.1.1
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: ADLaMDisplay-Regular
      fonts:
        - asset: assets/fonts/ADLaMDisplay-Regular.ttf
    - family: Rubik-VariableFont_wght
      fonts:
        - asset: assets/fonts/Rubik-VariableFont_wght.ttf
